"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var goalController_1 = require("./goalController");
var router = (0, express_1.Router)();
router.get("/", goalController_1.getGoalsController);
router.post("/", goalController_1.addGoalController);
router.patch("/:goalId", goalController_1.updateGoalController);
router.delete("/:goalId", goalController_1.deleteGoalController);
exports.default = router;
