"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var transactionController_1 = require("./transactionController");
var router = (0, express_1.Router)();
router.get("/balance", transactionController_1.getBalanceController);
router.get("/list", transactionController_1.getTransactionListController);
router.post("/", transactionController_1.addTransactionController);
router.get("/expenses-by-category", transactionController_1.getExpensesByCategoryController);
exports.default = router;
